/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Class.*;
import javax.swing.JOptionPane;

/**
 *
 * @author USER DK
 */
public class Menu extends javax.swing.JFrame {
    private banana kuning = new banana("Banana", 10000);
    private strawberry merah = new strawberry("Strawberry", 10000);
    private greentea hijau = new greentea("Greentea", 10000);
    private blueberry biru = new blueberry("Blueberry", 10000);
    private chocolate coklat = new chocolate("Chocolate", 10000);
    private vanilla putih = new vanilla("Vanilla", 10000);
    private cookies kue = new cookies("Cookies", 3000);
    private cheese keju = new cheese("Cheese", 3000);
    private coffee kopi = new coffee("Coffee", 3000);
    
    
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        kuningtxt.setText(String.valueOf(kuning.getBanana()));
        birutxt.setText(String.valueOf(biru.getBlueberry()));
        coklattxt.setText(String.valueOf(coklat.getChocolate()));
        hijautxt.setText(String.valueOf(hijau.getGreentea()));
        putihtxt.setText(String.valueOf(putih.getVanilla()));
        merahtxt.setText(String.valueOf(merah.getStrawberry()));
        cookiestxt.setText(String.valueOf(kue.getCookies()));
        cheesetxt.setText(String.valueOf(keju.getCheese()));
        coffeetxt.setText(String.valueOf(kopi.getCoffee()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        blueberry = new javax.swing.JLabel();
        chocolate = new javax.swing.JLabel();
        greentea = new javax.swing.JLabel();
        strawberry = new javax.swing.JLabel();
        vanilla = new javax.swing.JLabel();
        banana = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        birutxt = new javax.swing.JTextField();
        coklattxt = new javax.swing.JTextField();
        putihtxt = new javax.swing.JTextField();
        merahtxt = new javax.swing.JTextField();
        kuningtxt = new javax.swing.JTextField();
        cookiestxt = new javax.swing.JTextField();
        cheesetxt = new javax.swing.JTextField();
        coffeetxt = new javax.swing.JTextField();
        hijautxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        blue = new javax.swing.JLabel();
        choco = new javax.swing.JLabel();
        green = new javax.swing.JLabel();
        straw = new javax.swing.JLabel();
        vani = new javax.swing.JLabel();
        bana = new javax.swing.JLabel();
        plusblue = new javax.swing.JLabel();
        minblue = new javax.swing.JLabel();
        pluschoco = new javax.swing.JLabel();
        minchoco = new javax.swing.JLabel();
        plusgreen = new javax.swing.JLabel();
        mingreen = new javax.swing.JLabel();
        plusstraw = new javax.swing.JLabel();
        minstraw = new javax.swing.JLabel();
        plusbanana = new javax.swing.JLabel();
        minbanana = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cook = new javax.swing.JLabel();
        chee = new javax.swing.JLabel();
        coff = new javax.swing.JLabel();
        plusvanilla = new javax.swing.JLabel();
        minvanilla = new javax.swing.JLabel();
        pluscookies = new javax.swing.JLabel();
        mincookies = new javax.swing.JLabel();
        pluscheese = new javax.swing.JLabel();
        mincheese = new javax.swing.JLabel();
        pluscoffee = new javax.swing.JLabel();
        mincoffee = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel22.setText("jLabel22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\blubery.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\coklat.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\grinti.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\strobery.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        done.setText("DONE");
        done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneMouseClicked(evt);
            }
        });
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        getContentPane().add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        back.setText("BACK");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 184, 43, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("ORDER LIST  :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, -1, -1));

        blueberry.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        blueberry.setText("Blueberry     :");
        jPanel2.add(blueberry, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 78, -1));

        chocolate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        chocolate.setText("Chocolate     :");
        jPanel2.add(chocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 78, -1));

        greentea.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        greentea.setText("Greentea      :");
        jPanel2.add(greentea, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, 70, -1));

        strawberry.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        strawberry.setText("Strawberry   :");
        jPanel2.add(strawberry, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 152, 78, -1));

        vanilla.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vanilla.setText("Vanilla          :");
        jPanel2.add(vanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 70, -1));

        banana.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        banana.setText("Banana        :");
        jPanel2.add(banana, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, 78, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Cookies       :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 208, 78, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Cheese        :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 236, 78, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Coffee         :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 264, 78, -1));

        birutxt.setEditable(false);
        jPanel2.add(birutxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 35, 100, -1));

        coklattxt.setEditable(false);
        jPanel2.add(coklattxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 63, 100, -1));

        putihtxt.setEditable(false);
        jPanel2.add(putihtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 91, 100, -1));

        merahtxt.setEditable(false);
        merahtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahtxtActionPerformed(evt);
            }
        });
        jPanel2.add(merahtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 147, 100, -1));

        kuningtxt.setEditable(false);
        jPanel2.add(kuningtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 175, 100, -1));

        cookiestxt.setEditable(false);
        jPanel2.add(cookiestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 203, 100, -1));

        cheesetxt.setEditable(false);
        jPanel2.add(cheesetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 231, 100, -1));
        jPanel2.add(coffeetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 259, 100, -1));

        hijautxt.setEditable(false);
        hijautxt.setText(" ");
        jPanel2.add(hijautxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 119, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 210, 290));

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\vanila.png")); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\banana.png")); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        blue.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        blue.setText("Blueberry");
        getContentPane().add(blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        choco.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        choco.setText("Chocolate");
        getContentPane().add(choco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        green.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        green.setText("  Greentea");
        getContentPane().add(green, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 58, -1));

        straw.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        straw.setText(" Strawberry");
        getContentPane().add(straw, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 70, -1));

        vani.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        vani.setText(" Vanilla");
        getContentPane().add(vani, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 50, -1));

        bana.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        bana.setText(" Banana");
        getContentPane().add(bana, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 60, -1));

        plusblue.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\plus.png")); // NOI18N
        plusblue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusblueMouseClicked(evt);
            }
        });
        getContentPane().add(plusblue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        minblue.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\minus.png")); // NOI18N
        minblue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minblueMouseClicked(evt);
            }
        });
        getContentPane().add(minblue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        pluschoco.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\plus.png")); // NOI18N
        pluschoco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pluschocoMouseClicked(evt);
            }
        });
        getContentPane().add(pluschoco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        minchoco.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\minus.png")); // NOI18N
        minchoco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minchocoMouseClicked(evt);
            }
        });
        getContentPane().add(minchoco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        plusgreen.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\plus.png")); // NOI18N
        plusgreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusgreenMouseClicked(evt);
            }
        });
        getContentPane().add(plusgreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        mingreen.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\minus.png")); // NOI18N
        mingreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mingreenMouseClicked(evt);
            }
        });
        getContentPane().add(mingreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        plusstraw.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\plus.png")); // NOI18N
        plusstraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusstrawMouseClicked(evt);
            }
        });
        getContentPane().add(plusstraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        minstraw.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\minus.png")); // NOI18N
        minstraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minstrawMouseClicked(evt);
            }
        });
        getContentPane().add(minstraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        plusbanana.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\plus.png")); // NOI18N
        plusbanana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusbananaMouseClicked(evt);
            }
        });
        getContentPane().add(plusbanana, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        minbanana.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\minus.png")); // NOI18N
        minbanana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minbananaMouseClicked(evt);
            }
        });
        getContentPane().add(minbanana, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel27.setText("~ADD TOPPING : 3 K ");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        price.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        price.setText("~PRICE : 10 K");
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\cheese.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\coffee-beans.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\cookie (1).png")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        cook.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        cook.setText("Cookies");
        getContentPane().add(cook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        chee.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        chee.setText(" Cheese");
        getContentPane().add(chee, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 40, -1));

        coff.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        coff.setText("Coffee");
        getContentPane().add(coff, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        plusvanilla.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\plus.png")); // NOI18N
        plusvanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusvanillaMouseClicked(evt);
            }
        });
        getContentPane().add(plusvanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        minvanilla.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\minus.png")); // NOI18N
        minvanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minvanillaMouseClicked(evt);
            }
        });
        getContentPane().add(minvanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        pluscookies.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\plus.png")); // NOI18N
        pluscookies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pluscookiesMouseClicked(evt);
            }
        });
        getContentPane().add(pluscookies, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        mincookies.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\minus.png")); // NOI18N
        mincookies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mincookiesMouseClicked(evt);
            }
        });
        getContentPane().add(mincookies, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        pluscheese.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\plus.png")); // NOI18N
        pluscheese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pluscheeseMouseClicked(evt);
            }
        });
        getContentPane().add(pluscheese, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        mincheese.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\minus.png")); // NOI18N
        mincheese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mincheeseMouseClicked(evt);
            }
        });
        getContentPane().add(mincheese, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        pluscoffee.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\plus.png")); // NOI18N
        pluscoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pluscoffeeMouseClicked(evt);
            }
        });
        getContentPane().add(pluscoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        mincoffee.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER DK\\Documents\\NetBeansProjects\\ProjekFinal_1\\src\\main\\java\\IMG\\minus.png")); // NOI18N
        mincoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mincoffeeMouseClicked(evt);
            }
        });
        getContentPane().add(mincoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        jLabel9.setText("ICE CREAM MENU");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 380, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doneActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void merahtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merahtxtActionPerformed

    private void pluschocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pluschocoMouseClicked
        coklat.addChocolate();
        coklat.getTotal(coklat.getChocolate(), coklat.getHarga());
        coklattxt.setText(String.valueOf(coklat.getChocolate()));
    }//GEN-LAST:event_pluschocoMouseClicked

    private void plusblueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusblueMouseClicked
        biru.addBlueberry();
        biru.getTotal(biru.getBlueberry(), biru.getHarga());
        birutxt.setText(String.valueOf(biru.getBlueberry()));
    }//GEN-LAST:event_plusblueMouseClicked

    private void plusvanillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusvanillaMouseClicked
        putih.addVanilla();
        putih.getTotal(putih.getVanilla(), putih.getHarga());
        putihtxt.setText(String.valueOf(putih.getVanilla()));
    }//GEN-LAST:event_plusvanillaMouseClicked

    private void plusgreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusgreenMouseClicked
        hijau.addGreentea();
        hijau.getTotal(hijau.getGreentea(), hijau.getHarga());
        hijautxt.setText(String.valueOf(hijau.getGreentea()));
    }//GEN-LAST:event_plusgreenMouseClicked

    private void plusstrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusstrawMouseClicked
        merah.addStrawberry();
        merah.getTotal(merah.getStrawberry(), merah.getHarga());
        merahtxt.setText(String.valueOf(merah.getStrawberry()));
    }//GEN-LAST:event_plusstrawMouseClicked

    private void plusbananaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusbananaMouseClicked
        kuning.addBanana();
        kuning.getTotal(kuning.getBanana(), kuning.getHarga());
        kuningtxt.setText(String.valueOf(kuning.getBanana()));
    }//GEN-LAST:event_plusbananaMouseClicked

    private void pluscookiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pluscookiesMouseClicked
        kue.addCookies();
        kue.getTotal(kue.getCookies(), kue.getHarga());
        cookiestxt.setText(String.valueOf(kue.getCookies()));
    }//GEN-LAST:event_pluscookiesMouseClicked

    private void pluscheeseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pluscheeseMouseClicked
        keju.addCheese();
        keju.getTotal(keju.getCheese(), keju.getHarga());
        cheesetxt.setText(String.valueOf(keju.getCheese()));
    }//GEN-LAST:event_pluscheeseMouseClicked

    private void pluscoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pluscoffeeMouseClicked
        kopi.addCoffee();
        kopi.getTotal(kopi.getCoffee(), kopi.getHarga());
        coffeetxt.setText(String.valueOf(kopi.getCoffee()));
    }//GEN-LAST:event_pluscoffeeMouseClicked

    private void minblueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minblueMouseClicked
        if (biru.getBlueberry()-1 < 0) {
            JOptionPane.showMessageDialog(this, "Invalid input");
        } else{
            biru.minBlueberry();
        }
        biru.getTotal(biru.getBlueberry(), biru.getHarga());
        birutxt.setText(String.valueOf(biru.getBlueberry()));
    }//GEN-LAST:event_minblueMouseClicked

    private void minchocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minchocoMouseClicked
        if (coklat.getChocolate()-1 < 0) {
            JOptionPane.showMessageDialog(this, "Invalid input");
        } else{
            coklat.minChocolate();
        }
        coklat.getTotal(coklat.getChocolate(), coklat.getHarga());
        coklattxt.setText(String.valueOf(coklat.getChocolate()));
    }//GEN-LAST:event_minchocoMouseClicked

    private void minvanillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minvanillaMouseClicked
        if (putih.getVanilla()-1 < 0) {
            JOptionPane.showMessageDialog(this, "Invalid input");
        } else{
            putih.minVanilla();
        }
        putih.getTotal(putih.getVanilla(), putih.getHarga());
        putihtxt.setText(String.valueOf(putih.getVanilla()));
    }//GEN-LAST:event_minvanillaMouseClicked

    private void mingreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mingreenMouseClicked
       if (hijau.getGreentea()-1 < 0) {
            JOptionPane.showMessageDialog(this, "Invalid input");
        } else{
            hijau.minGreentea();
        }
        hijau.getTotal(hijau.getGreentea(), hijau.getHarga());
        hijautxt.setText(String.valueOf(hijau.getGreentea())); 
    }//GEN-LAST:event_mingreenMouseClicked

    private void minstrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minstrawMouseClicked
        if (merah.getStrawberry()-1 < 0) {
            JOptionPane.showMessageDialog(this, "Invalid input");
        } else{
            merah.minStrawberry();
        }
         merah.getTotal( merah.getStrawberry(),  merah.getHarga());
         merahtxt.setText(String.valueOf( merah.getStrawberry())); 
    }//GEN-LAST:event_minstrawMouseClicked

    private void minbananaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minbananaMouseClicked
        if (kuning.getBanana()-1 < 0) {
            JOptionPane.showMessageDialog(this, "Invalid input");
        } else{
            kuning.minBanana();
        }
         kuning.getTotal( kuning.getBanana(),  kuning.getHarga());
         kuningtxt.setText(String.valueOf( kuning.getBanana())); 
    }//GEN-LAST:event_minbananaMouseClicked

    private void mincookiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mincookiesMouseClicked
        if (kue.getCookies()-1 < 0) {
            JOptionPane.showMessageDialog(this, "Invalid input");
        } else{
            kue.minCookies();
        }
         kue.getTotal( kue.getCookies(),  kue.getHarga());
         cookiestxt.setText(String.valueOf( kue.getCookies())); 
    }//GEN-LAST:event_mincookiesMouseClicked

    private void mincheeseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mincheeseMouseClicked
        if (keju.getCheese()-1 < 0) {
            JOptionPane.showMessageDialog(this, "Invalid input");
        } else{
            keju.minCheese();
        }
         keju.getTotal( keju.getCheese(),  keju.getHarga());
         cheesetxt.setText(String.valueOf( keju.getCheese())); 
    }//GEN-LAST:event_mincheeseMouseClicked

    private void mincoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mincoffeeMouseClicked
        if (kopi.getCoffee()-1 < 0) {
            JOptionPane.showMessageDialog(this, "Invalid input");
        } else{
            kopi.minCoffee();
        }
         kopi.getTotal( kopi.getCoffee(),  kopi.getHarga());
         coffeetxt.setText(String.valueOf( kopi.getCoffee())); 
    }//GEN-LAST:event_mincoffeeMouseClicked

    private void doneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneMouseClicked
        int blueberry = biru.getSubTotal();
        int choco = coklat.getSubTotal();
        int vanilla = putih.getSubTotal();
        int grinti = hijau.getSubTotal();
        int stroberi = merah.getSubTotal();
        int pisang = kuning.getSubTotal();
        int kuki = kue.getSubTotal();
        int cis = keju.getSubTotal();
        int kohi = kopi.getSubTotal();
        
        int hasil = blueberry + choco + vanilla + grinti + stroberi + pisang + kuki + cis + kohi;
        
        Struk st = new Struk(kuning, biru, keju, coklat, kopi, kue, hijau, merah, putih,hasil);
        st.setVisible(true);
        dispose();
    }//GEN-LAST:event_doneMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Home tampilanawal = new Home();
        tampilanawal.setVisible(true);
        dispose();
    }//GEN-LAST:event_backMouseClicked
    public void clear(){
        kuning.setBanana(0);
        kuning.setJumlahPesan(0);
        kuning.setSubTotal(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bana;
    private javax.swing.JLabel banana;
    private javax.swing.JTextField birutxt;
    private javax.swing.JLabel blue;
    private javax.swing.JLabel blueberry;
    private javax.swing.JLabel chee;
    private javax.swing.JTextField cheesetxt;
    private javax.swing.JLabel choco;
    private javax.swing.JLabel chocolate;
    private javax.swing.JLabel coff;
    private javax.swing.JTextField coffeetxt;
    private javax.swing.JTextField coklattxt;
    private javax.swing.JLabel cook;
    private javax.swing.JTextField cookiestxt;
    private javax.swing.JButton done;
    private javax.swing.JLabel green;
    private javax.swing.JLabel greentea;
    private javax.swing.JTextField hijautxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kuningtxt;
    private javax.swing.JTextField merahtxt;
    private javax.swing.JLabel minbanana;
    private javax.swing.JLabel minblue;
    private javax.swing.JLabel mincheese;
    private javax.swing.JLabel minchoco;
    private javax.swing.JLabel mincoffee;
    private javax.swing.JLabel mincookies;
    private javax.swing.JLabel mingreen;
    private javax.swing.JLabel minstraw;
    private javax.swing.JLabel minvanilla;
    private javax.swing.JLabel plusbanana;
    private javax.swing.JLabel plusblue;
    private javax.swing.JLabel pluscheese;
    private javax.swing.JLabel pluschoco;
    private javax.swing.JLabel pluscoffee;
    private javax.swing.JLabel pluscookies;
    private javax.swing.JLabel plusgreen;
    private javax.swing.JLabel plusstraw;
    private javax.swing.JLabel plusvanilla;
    private javax.swing.JLabel price;
    private javax.swing.JTextField putihtxt;
    private javax.swing.JLabel straw;
    private javax.swing.JLabel strawberry;
    private javax.swing.JLabel vani;
    private javax.swing.JLabel vanilla;
    // End of variables declaration//GEN-END:variables
}
